credentials:
  usernames:
    jsmith:
      email: elhayefrat@gmail.com
      name: Elhay Efrat
      password: abc # To be replaced with hashed password
    rbriggs:
      email: shahar@gmail.com
      name: Shahar Best 
      password: abc # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
